[package]
name = "t-asci"
version = "0.1.0"
authors = ["Max Ilinov <ilimaksim@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
date_time = "2.1.0"
ron = "0.6.2"
fsio = "0.1.3"
